/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mypackage.MainForm.conn;
/**
 *
 * @author Володимир
 */
public class AgentsForm extends javax.swing.JFrame {

    /**
     * Creates new form AgentsForm
     */
    public AgentsForm() {
        initComponents();
        tableUpdate("SELECT * FROM `agents`;");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameAgent = new javax.swing.JTextField();
        txtEmailAgent = new javax.swing.JTextField();
        txtPhoneAgent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonNew = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSortName = new javax.swing.JButton();
        btnSortEmail = new javax.swing.JButton();
        btnSortPhone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Турагентство | Агенти");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Дані", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setText("Email:");

        jLabel3.setText("Телефон:");

        jLabel1.setText("Ім'я:");

        buttonNew.setText("Новий");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonEdit.setText("Редагувати");
        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setText("Видалити");
        buttonDelete.setEnabled(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonSearch.setText("Пошук");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameAgent)
                            .addComponent(txtEmailAgent)
                            .addComponent(txtPhoneAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(buttonNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNew)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSearch))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Агенти");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "name_agent", "email_agent", "phone_agent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSortName.setText("•");
        btnSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortNameActionPerformed(evt);
            }
        });

        btnSortEmail.setText("•");
        btnSortEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortEmailActionPerformed(evt);
            }
        });

        btnSortPhone.setText("•");
        btnSortPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnSortName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortEmail)
                        .addGap(152, 152, 152)
                        .addComponent(btnSortPhone)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSortName)
                            .addComponent(btnSortEmail)
                            .addComponent(btnSortPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PreparedStatement ps;
    int sortName = 0, sortEmail = 0, sortPhone = 0;
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        // TODO add your handling code here:
        String nameText = txtNameAgent.getText();
        String emailText = txtEmailAgent.getText();
        String phoneText = txtPhoneAgent.getText();
        
        if (!"".equals(nameText) && !"".equals(emailText) && !"".equals(phoneText)) {
        
            try {
                ps = conn.prepareStatement("INSERT INTO `agents`(name_agent, email_agent, phone_agent) VALUES(?, ?, ?);");
                ps.setString(1, nameText);
                ps.setString(2, emailText);
                ps.setString(3, phoneText);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Додано агента");
                tableUpdate("SELECT * FROM `agents`;");
                
                txtNameAgent.setText("");
                txtEmailAgent.setText("");
                txtPhoneAgent.setText("");
                txtNameAgent.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(AgentsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        String name = df.getValueAt(selectedIndex, 0).toString();
        String nameText = txtNameAgent.getText();
        String emailText = txtEmailAgent.getText();
        String phoneText = txtPhoneAgent.getText();
        
        if (!"".equals(nameText) && !"".equals(emailText) && !"".equals(phoneText)) {
        
            try {
                ps = conn.prepareStatement("UPDATE `agents` SET name_agent=?, email_agent=?, phone_agent=? WHERE name_agent=?;");
                ps.setString(1, nameText);
                ps.setString(2, emailText);
                ps.setString(3, phoneText);
                ps.setString(4, name);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Відредаговано агента");
                tableUpdate("SELECT * FROM `agents`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtNameAgent.setText("");
                txtEmailAgent.setText("");
                txtPhoneAgent.setText("");
                txtNameAgent.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(AgentsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        String nameText = txtNameAgent.getText();
        String emailText = txtEmailAgent.getText();
        String phoneText = txtPhoneAgent.getText();
        String ps = "SELECT * FROM `agents` WHERE `name_agent` LIKE ('%"
                + nameText + "%') AND `email_agent` LIKE ('%"
                + emailText + "%') AND `phone_agent` LIKE ('%"
                + phoneText + "%');";
        System.out.println(ps);
        tableUpdate(ps);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        txtNameAgent.setText(df.getValueAt(selectedIndex, 0).toString());
        txtEmailAgent.setText(df.getValueAt(selectedIndex, 1).toString());
        txtPhoneAgent.setText(df.getValueAt(selectedIndex, 2).toString());
        buttonEdit.setEnabled(true);
        buttonDelete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        String name = df.getValueAt(selectedIndex, 0).toString();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Ви хочете видалити агента на ім'я " + name + "?", "Видалення запису", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                ps = conn.prepareStatement("DELETE FROM `agents` WHERE name_agent=?;");
                ps.setString(1, name);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Агента видалено");
                tableUpdate("SELECT * FROM `agents`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtNameAgent.setText("");
                txtEmailAgent.setText("");
                txtPhoneAgent.setText("");
                txtNameAgent.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(AgentsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void btnSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortNameActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortName % 3 == 0) {
            order = " ORDER BY name_agent ASC;";
            text = "▼";
        } 
        if (sortName % 3 == 1) {
            order = " ORDER BY name_agent DESC;";
            text = "▲";
        }
        if (sortName % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortEmail.setText("•");
        btnSortPhone.setText("•");
        sortEmail = 0;
        sortPhone = 0;
        btnSortName.setText(text);
        sortName++;
        String q = "SELECT * FROM `agents`" + order;
        tableUpdate(q);
    }//GEN-LAST:event_btnSortNameActionPerformed

    private void btnSortEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortEmailActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortEmail % 3 == 0) {
            order = " ORDER BY email_agent ASC;";
            text = "▼";
        } 
        if (sortEmail % 3 == 1) {
            order = " ORDER BY email_agent DESC;";
            text = "▲";
        }
        if (sortEmail % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortPhone.setText("•");
        sortName = 0;
        sortPhone = 0;
        btnSortEmail.setText(text);
        sortEmail++;
        String q = "SELECT * FROM `agents`" + order;
        tableUpdate(q);
    }//GEN-LAST:event_btnSortEmailActionPerformed

    private void btnSortPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortPhoneActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortPhone % 3 == 0) {
            order = " ORDER BY phone_agent ASC;";
            text = "▼";
        } 
        if (sortPhone % 3 == 1) {
            order = " ORDER BY phone_agent DESC;";
            text = "▲";
        }
        if (sortPhone % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortEmail.setText("•");
        btnSortName.setText("•");
        sortEmail = 0;
        sortName = 0;
        btnSortPhone.setText(text);
        sortPhone++;
        String q = "SELECT * FROM `agents`" + order;
        tableUpdate(q);
    }//GEN-LAST:event_btnSortPhoneActionPerformed

    private void tableUpdate(String query) {
        int c;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData meta = rs.getMetaData();
            c = meta.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()) {
                Vector v = new Vector();
                for (int i = 1; i <= c; i++) {
                    v.add(rs.getString("name_agent"));
                    v.add(rs.getString("email_agent"));
                    v.add(rs.getString("phone_agent"));
                }
                df.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AgentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
//    private void tableHeaderMouseListener() {
//        JTableHeader header = jTable1.getTableHeader();
//        header.addMouseListener(new TableHeaderMouseListener(jTable1));
//    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgentsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortEmail;
    private javax.swing.JButton btnSortName;
    private javax.swing.JButton btnSortPhone;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmailAgent;
    private javax.swing.JTextField txtNameAgent;
    private javax.swing.JTextField txtPhoneAgent;
    // End of variables declaration//GEN-END:variables
}
