/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mypackage.MainForm.conn;
/**
 *
 * @author Володимир
 */
public class CustomersForm extends javax.swing.JFrame {

    /**
     * Creates new form AgentsForm
     */
    public CustomersForm() {
        initComponents();
        tableUpdate("SELECT * FROM `customers`;");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonNew = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSortId = new javax.swing.JButton();
        btnSortName = new javax.swing.JButton();
        btnSortEmail = new javax.swing.JButton();
        btnSortPhone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Турагентство | Агенти");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Дані", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setText("Ім'я:");

        jLabel3.setText("Email:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Номер паспорта:");

        buttonNew.setText("Новий");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonEdit.setText("Редагувати");
        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setText("Видалити");
        buttonDelete.setEnabled(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonSearch.setText("Пошук");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Телефон:");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtName)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPhone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(buttonNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNew)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSearch))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Замовники");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "passport_id", "name_customer", "email_customer", "phone_customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSortId.setText("•");
        btnSortId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortIdActionPerformed(evt);
            }
        });

        btnSortName.setText("•");
        btnSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortNameActionPerformed(evt);
            }
        });

        btnSortEmail.setText("•");
        btnSortEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortEmailActionPerformed(evt);
            }
        });

        btnSortPhone.setText("•");
        btnSortPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnSortId)
                        .addGap(103, 103, 103)
                        .addComponent(btnSortName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortEmail)
                        .addGap(101, 101, 101)
                        .addComponent(btnSortPhone)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSortId)
                            .addComponent(btnSortName)
                            .addComponent(btnSortEmail)
                            .addComponent(btnSortPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PreparedStatement ps;
    int sortId = 0, sortName = 0, sortEmail = 0, sortPhone = 0;
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String name = txtName.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        
        if (!"".equals(id) && !"".equals(name) && !"".equals(email) && !"".equals(phone)) {
        
            try {
                ps = conn.prepareStatement("INSERT INTO `customers`(passport_id, name_customer, email_customer, phone_customer) VALUES(?, ?, ?, ?);");
                ps.setString(1, id);
                ps.setString(2, name);
                ps.setString(3, email);
                ps.setString(4, phone);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Додано замовника");
                tableUpdate("SELECT * FROM `customers`;");
                
                txtId.setText("");
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtId.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(CustomersForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        String id = df.getValueAt(selectedIndex, 0).toString();
        String idText = txtId.getText();
        String nameText = txtName.getText();
        String emailText = txtEmail.getText();
        String phoneText = txtPhone.getText();
        
        if (!"".equals(idText) && !"".equals(nameText) && !"".equals(emailText) && !"".equals(phoneText)) {
        
            try {
                ps = conn.prepareStatement("UPDATE `customers` SET passport_id=?, name_customer=?, email_customer=?, phone_customer=? WHERE passport_id=?;");
                ps.setString(1, idText);
                ps.setString(2, nameText);
                ps.setString(3, emailText);
                ps.setString(4, phoneText);
                ps.setString(5, id);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Відредаговано дані замовника");
                tableUpdate("SELECT * FROM `customers`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtId.setText("");
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtId.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(CustomersForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        String idText = txtId.getText();
        String nameText = txtName.getText();
        String emailText = txtEmail.getText();
        String phoneText = txtPhone.getText();
        String ps = "SELECT * FROM `customers` WHERE `passport_id` LIKE ('%"
                + idText + "%') AND `name_customer` LIKE ('%"
                + nameText + "%') AND `email_customer` LIKE ('%"
                + emailText + "%') AND `phone_customer` LIKE ('%"
                + phoneText + "%');";
        System.out.println(ps);
        tableUpdate(ps);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        txtId.setText(df.getValueAt(selectedIndex, 0).toString());
        txtName.setText(df.getValueAt(selectedIndex, 1).toString());
        txtEmail.setText(df.getValueAt(selectedIndex, 2).toString());
        txtPhone.setText(df.getValueAt(selectedIndex, 3).toString());
        buttonEdit.setEnabled(true);
        buttonDelete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        String id = df.getValueAt(selectedIndex, 0).toString();
        String name = df.getValueAt(selectedIndex, 1).toString();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Ви хочете видалити дані замовника " + name + "?", "Видалення запису", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                ps = conn.prepareStatement("DELETE FROM `customers` WHERE passport_id=?;");
                ps.setString(1, id);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Дані замовника видалено");
                tableUpdate("SELECT * FROM `customers`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtId.setText("");
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtId.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(CustomersForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void btnSortIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortIdActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortId % 3 == 0) {
            order = " ORDER BY passport_id ASC;";
            text = "▼";
        } 
        if (sortId % 3 == 1) {
            order = " ORDER BY passport_id DESC;";
            text = "▲";
        }
        if (sortId % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortEmail.setText("•");
        btnSortPhone.setText("•");
        sortName = 0;
        sortEmail = 0;
        sortPhone = 0;
        btnSortId.setText(text);
        sortId++;
        String q = "SELECT * FROM `customers`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortIdActionPerformed

    private void btnSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortNameActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortName % 3 == 0) {
            order = " ORDER BY name_customer ASC;";
            text = "▼";
        } 
        if (sortName % 3 == 1) {
            order = " ORDER BY name_customer DESC;";
            text = "▲";
        }
        if (sortName % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortId.setText("•");
        btnSortEmail.setText("•");
        btnSortPhone.setText("•");
        sortId = 0;
        sortEmail = 0;
        sortPhone = 0;
        btnSortName.setText(text);
        sortName++;
        String q = "SELECT * FROM `customers`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortNameActionPerformed

    private void btnSortEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortEmailActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortEmail % 3 == 0) {
            order = " ORDER BY email_customer ASC;";
            text = "▼";
        } 
        if (sortEmail % 3 == 1) {
            order = " ORDER BY email_customer DESC;";
            text = "▲";
        }
        if (sortEmail % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortId.setText("•");
        btnSortPhone.setText("•");
        sortName = 0;
        sortId = 0;
        sortPhone = 0;
        btnSortEmail.setText(text);
        sortEmail++;
        String q = "SELECT * FROM `customers`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnSortPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortPhoneActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortPhone % 3 == 0) {
            order = " ORDER BY phone_customer ASC;";
            text = "▼";
        } 
        if (sortPhone % 3 == 1) {
            order = " ORDER BY phone_customer DESC;";
            text = "▲";
        }
        if (sortPhone % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortId.setText("•");
        btnSortEmail.setText("•");
        sortName = 0;
        sortId = 0;
        sortEmail = 0;
        btnSortPhone.setText(text);
        sortPhone++;
        String q = "SELECT * FROM `customers`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortPhoneActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tableUpdate(String query) {
        int c;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData meta = rs.getMetaData();
            c = meta.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()) {
                Vector v = new Vector();
                for (int i = 1; i <= c; i++) {
                    v.add(rs.getString("passport_id"));
                    v.add(rs.getString("name_customer"));
                    v.add(rs.getString("email_customer"));
                    v.add(rs.getString("phone_customer"));
                }
                df.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
//    private void tableHeaderMouseListener() {
//        JTableHeader header = jTable1.getTableHeader();
//        header.addMouseListener(new TableHeaderMouseListener(jTable1));
//    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgentsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortEmail;
    private javax.swing.JButton btnSortId;
    private javax.swing.JButton btnSortName;
    private javax.swing.JButton btnSortPhone;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
