/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mypackage.MainForm.conn;
/**
 *
 * @author Володимир
 */
public class ToursForm extends javax.swing.JFrame {

    /**
     * Creates new form AgentsForm
     */
    public ToursForm() {
        initComponents();
        tableUpdate("SELECT * FROM `tours`;");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOper = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonNew = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSortOper = new javax.swing.JButton();
        btnSortName = new javax.swing.JButton();
        btnSortPrice = new javax.swing.JButton();
        btnSortLocation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Турагентство | Агенти");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Дані", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setText("Назва туру:");

        jLabel3.setText("Ціна:");

        jLabel1.setText("Туроператор:");

        buttonNew.setText("Новий");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonEdit.setText("Редагувати");
        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setText("Видалити");
        buttonDelete.setEnabled(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonSearch.setText("Пошук");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Локація:");

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOper)
                            .addComponent(txtName)
                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtLocation)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(buttonNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNew)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSearch))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Тури");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "touroperator", "name_tour", "price", "location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSortOper.setText("•");
        btnSortOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortOperActionPerformed(evt);
            }
        });

        btnSortName.setText("•");
        btnSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortNameActionPerformed(evt);
            }
        });

        btnSortPrice.setText("•");
        btnSortPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortPriceActionPerformed(evt);
            }
        });

        btnSortLocation.setText("•");
        btnSortLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnSortOper)
                        .addGap(103, 103, 103)
                        .addComponent(btnSortName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortPrice)
                        .addGap(103, 103, 103)
                        .addComponent(btnSortLocation)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSortOper)
                            .addComponent(btnSortName)
                            .addComponent(btnSortPrice)
                            .addComponent(btnSortLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PreparedStatement ps;
    int sortOper = 0, sortName = 0, sortPrice = 0, sortLocation = 0;
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        // TODO add your handling code here:
        String oper = txtOper.getText();
        String name = txtName.getText();
        String price = txtPrice.getText();
        String location = txtLocation.getText();
        
        if (!"".equals(oper) && !"".equals(name) && !"".equals(price) && !"".equals(location)) {
        
            try {
                ps = conn.prepareStatement("INSERT INTO `tours`(touroperator, name_tour, price, location) VALUES(?, ?, ?, ?);");
                ps.setString(1, oper);
                ps.setString(2, name);
                ps.setString(3, price);
                ps.setString(4, location);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Додано тур");
                tableUpdate("SELECT * FROM `tours`;");
                
                txtOper.setText("");
                txtName.setText("");
                txtPrice.setText("");
                txtLocation.setText("");
                txtOper.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(ToursForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        String oper = df.getValueAt(selectedIndex, 0).toString();
        String name = df.getValueAt(selectedIndex, 1).toString();
        String operText = txtOper.getText();
        String nameText = txtName.getText();
        String priceText = txtPrice.getText();
        String locationText = txtLocation.getText();
        
        if (!"".equals(operText) && !"".equals(nameText) && !"".equals(priceText) && !"".equals(locationText)) {
        
            try {
                ps = conn.prepareStatement("UPDATE `tours` SET touroperator=?, name_tour=?, price=?, location=? WHERE touroperator=? AND name_tour=?;");
                ps.setString(1, operText);
                ps.setString(2, nameText);
                ps.setString(3, priceText);
                ps.setString(4, locationText);
                ps.setString(5, oper);
                ps.setString(6, name);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Відредаговано тур");
                tableUpdate("SELECT * FROM `tours`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtOper.setText("");
                txtName.setText("");
                txtPrice.setText("");
                txtLocation.setText("");
                txtOper.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(ToursForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        String operText = txtOper.getText();
        String nameText = txtName.getText();
        String priceText = txtPrice.getText();
        String locationText = txtLocation.getText();
        String ps = "SELECT * FROM `tours` WHERE `touroperator` LIKE ('%"
                + operText + "%') AND `name_tour` LIKE ('%"
                + nameText + "%') AND `price` LIKE ('%"
                + priceText + "%') AND `location` LIKE ('%"
                + locationText + "%');";
        System.out.println(ps);
        tableUpdate(ps);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        txtOper.setText(df.getValueAt(selectedIndex, 0).toString());
        txtName.setText(df.getValueAt(selectedIndex, 1).toString());
        txtPrice.setText(df.getValueAt(selectedIndex, 2).toString());
        txtLocation.setText(df.getValueAt(selectedIndex, 3).toString());
        buttonEdit.setEnabled(true);
        buttonDelete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        String oper = df.getValueAt(selectedIndex, 0).toString();
        String name = df.getValueAt(selectedIndex, 1).toString();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Ви хочете видалити тур \"" + name + "\"?", "Видалення запису", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                ps = conn.prepareStatement("DELETE FROM `tours` WHERE touroperator=? AND name_tour=?;");
                ps.setString(1, oper);
                ps.setString(2, name);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Тур видалено");
                tableUpdate("SELECT * FROM `tours`;");
                
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                txtOper.setText("");
                txtName.setText("");
                txtPrice.setText("");
                txtLocation.setText("");
                txtOper.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(ToursForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void btnSortOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortOperActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortOper % 3 == 0) {
            order = " ORDER BY touroperator ASC;";
            text = "▼";
        } 
        if (sortOper % 3 == 1) {
            order = " ORDER BY touroperator DESC;";
            text = "▲";
        }
        if (sortOper % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortPrice.setText("•");
        btnSortLocation.setText("•");
        sortName = 0;
        sortPrice = 0;
        sortLocation = 0;
        btnSortOper.setText(text);
        sortOper++;
        String q = "SELECT * FROM `tours`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortOperActionPerformed

    private void btnSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortNameActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortName % 3 == 0) {
            order = " ORDER BY name_tour ASC;";
            text = "▼";
        } 
        if (sortName % 3 == 1) {
            order = " ORDER BY name_tour DESC;";
            text = "▲";
        }
        if (sortName % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortOper.setText("•");
        btnSortPrice.setText("•");
        btnSortLocation.setText("•");
        sortOper = 0;
        sortPrice = 0;
        sortLocation = 0;
        btnSortName.setText(text);
        sortName++;
        String q = "SELECT * FROM `tours`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortNameActionPerformed

    private void btnSortPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortPriceActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortPrice % 3 == 0) {
            order = " ORDER BY price ASC;";
            text = "▼";
        } 
        if (sortPrice % 3 == 1) {
            order = " ORDER BY price DESC;";
            text = "▲";
        }
        if (sortPrice % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortOper.setText("•");
        btnSortLocation.setText("•");
        sortName = 0;
        sortOper = 0;
        sortLocation = 0;
        btnSortPrice.setText(text);
        sortPrice++;
        String q = "SELECT * FROM `tours`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortPriceActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void btnSortLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortLocationActionPerformed
        // TODO add your handling code here:
        String order = new String();
        String text = new String();
        if (sortLocation % 3 == 0) {
            order = " ORDER BY location ASC;";
            text = "▼";
        } 
        if (sortLocation % 3 == 1) {
            order = " ORDER BY location DESC;";
            text = "▲";
        }
        if (sortLocation % 3 == 2) {
            order = ";";
            text = "•";
        }
        btnSortName.setText("•");
        btnSortOper.setText("•");
        btnSortPrice.setText("•");
        sortName = 0;
        sortOper = 0;
        sortPrice = 0;
        btnSortLocation.setText(text);
        sortLocation++;
        String q = "SELECT * FROM `tours`" + order;
        buttonEdit.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableUpdate(q);
    }//GEN-LAST:event_btnSortLocationActionPerformed

    private void tableUpdate(String query) {
        int c;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData meta = rs.getMetaData();
            c = meta.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()) {
                Vector v = new Vector();
                for (int i = 1; i <= c; i++) {
                    v.add(rs.getString("touroperator"));
                    v.add(rs.getString("name_tour"));
                    v.add(rs.getString("price"));
                    v.add(rs.getString("location"));
                }
                df.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ToursForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
//    private void tableHeaderMouseListener() {
//        JTableHeader header = jTable1.getTableHeader();
//        header.addMouseListener(new TableHeaderMouseListener(jTable1));
//    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgentsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortLocation;
    private javax.swing.JButton btnSortName;
    private javax.swing.JButton btnSortOper;
    private javax.swing.JButton btnSortPrice;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOper;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
